#=====================================
FROM boysanic/boinc-server-docker-makeproject:latest
#=====================================

COPY --chown=1000 project $PROJECT_ROOT
COPY --chown=1000 secrets.env /run/secrets/